apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: my-web-app
spec:
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
