apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: my-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: web-container
          image: nginx:1.14.2
          ports:
            - containerPort: 80
