apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: default
data:
  database_url: jdbc:mysql://mydatabase.example.com:3306/mydatabase
  database_user: user_example
  config.json: |
    {
        "key": "value",
        "jsonKey": {
            "subKey": "subValue"
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
  annotations:
    kubernetes.io/description: "Sensitive database credentials"
type: Opaque
data:
  password: cGFzc3dvcmRTZWNyZXQ=  # Example: echo -n 'passwordSecret' | base64
  token: dG9rZW5TZWNyZXQ=        # Example: echo -n 'tokenSecret' | base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-container
          image: nginx
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: database_url
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-secret
                  key: password
            - name: DATABASE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: example-secret
                  key: token
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: example-configmap


# This YAML script combines a ConfigMap, a Secret, and a Deployment to securely configure an application with sensitive and non-sensitive data. Environment variables and a mounted volume are used for configuration access.

# K8s Secrets: https://kubernetes.io/docs/concepts/configuration/secret/

# K8s ConfigMaps: https://kubernetes.io/docs/concepts/configuration/configmap/

