apiVersion: v1
kind: Pod
metadata:
  name: liveness-readiness-pod
  namespace: default
spec:
  containers:
    - name: mycontainer
      image: example-image:latest
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 5
        failureThreshold: 3


# This configuration addresses high pod restart rates by defining resource requests and limits, as well as liveness and readiness probes to ensure pod health and stability.

# For more details on liveness and readiness probes: https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/