apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: example-namespace
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "8"
    limits.memory: 10Gi


# This ResourceQuota enforces the following constraints within the example-namespace namespace:

#     A maximum of 10 pods.
#     Total CPU requests not exceeding 4 cores.
#     Total memory requests not exceeding 5 GiB.
#     Total CPU limits not exceeding 8 cores.
#     Total memory limits not exceeding 10 GiB.

# For more information on configuring resource quotas in Kubernetes, refer to the official documentation: https://kubernetes.io/docs/concepts/policy/resource-quotas/