apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: none
  disk-encryption: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: io-intensive-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: io-intensive
  template:
    metadata:
      labels:
        app: io-intensive
    spec:
      containers:
        - name: io-intensive-container
          image: io-intensive-image
          volumeMounts:
            - mountPath: "/data"
              name: io-data-volume
      volumes:
        - name: io-data-volume
          persistentVolumeClaim:
            claimName: example-pvc


# This YAML defines a StorageClass named fast-storage configured for SSD storage, a PersistentVolumeClaim bound to this storage class, and a deployment that mounts the volume for I/O-intensive workloads.

# For more details on StorageClass: https://kubernetes.io/docs/concepts/storage/storage-classes/

# For more details on PersistentVolume: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
