apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: example-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: example-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 128Mi
        maxAllowed:
          cpu: 2
          memory: 4Gi


# This configuration enables Vertical Pod Autoscaling for the example-deployment in the default namespace, allowing automatic adjustment of CPU and memory resources within the specified limits.

# For more information on configuring Vertical Pod Autoscaler in Kubernetes, refer to the official documentation: https://kubernetes.io/docs/concepts/workloads/autoscaling/