apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-resourcequota
  namespace: default
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
