apiVersion: v1
kind: Service
metadata:
  name: my-external-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: my-app-image:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20


# This configuration defines a LoadBalancer service named my-external-service that exposes your application externally on port 80, forwarding traffic to port 8080 on the targeted pods. The associated deployment, my-app-deployment, consists of three replicas of my-app-container, each configured with readiness and liveness probes to monitor the application's health. The readiness probe checks the /healthz endpoint every 10 seconds after an initial delay of 5 seconds to determine if the pod is ready to accept traffic. The liveness probe checks the same endpoint every 20 seconds after an initial delay of 15 seconds to verify that the application is running properly.

# For more information on configuring liveness and readiness probes, refer to the official Kubernetes documentation: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/